spring:
  datasource:
    username: 
    url: 
    password: ${{secrets.DB_PASSWORD}}

library-app:
  uri: https://library-app-12-factor-app.herokuapp.com
    
senior:
  citizen: James
junior:
  citizen: Bond