spring:
  datasource:
    username: root
    url: jdbc:mysql://mysqldb:3306/customerportallibrary
    password: root
  jpa:
    generate-ddl: true

library-app:
  uri: https://localhost:8700/
    
senior:
  citizen: James
junior:
  citizen: Bond

