spring:
  datasource:
    username: root
    url: jdbc:mysql://mysqldb:3306/customerportallibrary
    password: root
  jpa:
    generate-ddl: false
    
server:
  port: 8081

library-app:
  uri: http://library-app:8080/
    
senior:
  citizen: Mahabharat
junior:
  citizen: Bond

auth:
  password: adminpassword
