spring:
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_URL}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    generate-ddl: false

library-app:
  uri: https://library-app-12-factor-app.herokuapp.com
    
senior:
  citizen: Mahabharat
junior:
  citizen: 2 States

auth:
  password: ${PASSWORD}
