spring:
  datasource:
    username: ${secrets.JDBC_DATABASE_USERNAME}
    url: ${secrets.JDBC_DATABASE_URL}
    password: ${secrets.JDBC_DATABASE_PASSWORD}
  jpa:
    generate-ddl: true

library-app:
  uri: https://localhost:8700/
    
senior:
  citizen: James
junior:
  citizen: Bond

auth:
  password: ${PASSWORD}
